/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pots/scene.gltf 
Author: codyyy (https://sketchfab.com/codyyy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cluster-of-ancient-pots-4be96f412cfa4677abed7b69d216f8ea
Title: Cluster Of Ancient Pots
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/pots/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={100}>
          <mesh geometry={nodes.input_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.input_Material001_0_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.input_Material001_0_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.input_Material001_0_3.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.input_Material001_0_4.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/pots/scene.gltf')
